In [15]:
from pathlib import Path
from collections import Counter
import optuna
from rectools.models import  PopularModel
from implicit.nearest_neighbours import CosineRecommender, BM25Recommender, TFIDFRecommender
from rectools.models.implicit_knn import ImplicitItemKNNWrapperModel
from rectools.dataset import Dataset
from rectools import Columns
from rectools.metrics import Precision, Recall, MAP, calc_metrics, MeanInvUserFreq, Serendipity
from rectools.model_selection import TimeRangeSplitter

import dill
import json
from pprint import pprint
import numpy as np
import scipy as sp
import time
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [5]:
DATA_PATH = Path("../data/kion_train")

In [6]:
users = pd.read_csv(DATA_PATH / 'users.csv')
items = pd.read_csv(DATA_PATH / 'items.csv')
interactions = pd.read_csv(DATA_PATH / 'interactions.csv')

In [7]:
# rename columns, convert timestamp
interactions.rename(columns={'last_watch_dt': Columns.Datetime,
                            'total_dur': Columns.Weight},
                    inplace=True)

interactions['datetime'] = pd.to_datetime(interactions['datetime'])

In [8]:
interactions.head()

   user_id  item_id   datetime  weight  watched_pct
0   176549     9506 2021-05-11    4250         72.0
1   699317     1659 2021-05-29    8317        100.0
2   656683     7107 2021-05-09      10          0.0
3   864613     7638 2021-07-05   14483        100.0
4   964868     9506 2021-04-30    6725        100.0

In [9]:
dataset = Dataset.construct(
    interactions_df=interactions,
    user_features_df=None,
    item_features_df=None
)

In [14]:
n_folds = 1
unit = "D"
n_units = 7
periods = n_folds + 1
freq = f"{n_units}{unit}"



# generator of folds
cv = TimeRangeSplitter(
    test_size=freq,
    n_splits=n_folds,
    filter_already_seen=True,
    filter_cold_items=True,
    filter_cold_users=True,
)

In [16]:
(train_ids, test_ids, fold_info) = next(cv.split(dataset.interactions, collect_fold_stats=True))

In [17]:
train_ids

array([      0,       1,       2, ..., 5476247, 5476249, 5476250])

In [18]:
train = interactions.loc[train_ids]
test = interactions.loc[test_ids]

In [19]:
test

         user_id  item_id   datetime  weight  watched_pct
9         203219    13582 2021-08-22    6975        100.0
54        200197     9335 2021-08-16      83          2.0
64         73446    14488 2021-08-19    6011        100.0
94        890735    14200 2021-08-16    1179         28.0
110      1053892     1916 2021-08-21    6502        100.0
...          ...      ...        ...     ...          ...
5476159  1039219     3071 2021-08-22    3808         65.0
5476169   589589      983 2021-08-21    2403         43.0
5476188   590892     8618 2021-08-21    1335         23.0
5476191   857162    12360 2021-08-16      11          0.0
5476201   273558    10605 2021-08-21   34030        100.0

[298878 rows x 5 columns]

In [20]:
item_knn = ImplicitItemKNNWrapperModel(model=CosineRecommender(K=30))
item_knn.fit(dataset);

In [21]:
# take a look at the recommended items by the simple itemknn model
recs_itemknn = item_knn.recommend(
    test['user_id'].unique(),
    dataset=dataset,
    k=10,
    filter_viewed=False  # False - same items to every user
)

In [22]:
recs_itemknn.head()

   user_id  item_id        score  rank
0   203219     4976  8768.000001     1
1   203219    13865  7718.612431     2
2   203219    13582  6975.000056     3
3   203219     4880  5075.790326     4
4   203219     6936  3063.454010     5

## Обучение userKnn с различными мерами расстояния

In [23]:
max_date = interactions[Columns.Datetime].max()

In [24]:
interactions[Columns.Weight] = np.where(interactions['watched_pct'] > 10, 3, 1)

In [25]:
train = interactions[interactions[Columns.Datetime] < max_date - pd.Timedelta(days=7)].copy()
test = interactions[interactions[Columns.Datetime] >= max_date - pd.Timedelta(days=7)].copy()

print(f"train: {train.shape}")
print(f"test: {test.shape}")

train: (4985269, 5)
test: (490982, 5)

In [26]:
cold_users = set(test[Columns.User]) - set(train[Columns.User])

In [27]:
test.drop(test[test[Columns.User].isin(cold_users)].index, inplace=True)

In [29]:
users.fillna('Unknown', inplace=True)

In [30]:
users = users.loc[users[Columns.User].isin(train[Columns.User])].copy()

In [31]:
users

        user_id         age        income      sex  kids_flg
0        973171   age_25_34  income_60_90        М         1
1        962099   age_18_24  income_20_40        М         0
3        721985   age_45_54  income_20_40        Ж         0
4        704055   age_35_44  income_60_90        Ж         0
5       1037719   age_45_54  income_60_90        М         0
...         ...         ...           ...      ...       ...
840188   312839  age_65_inf  income_60_90        Ж         0
840189   191349   age_45_54  income_40_60        М         1
840190   393868   age_25_34  income_20_40        М         0
840192   339025  age_65_inf   income_0_20        Ж         0
840194   251008     Unknown       Unknown  Unknown         0

[697136 rows x 5 columns]

In [32]:
user_features_frames = []
for feature in ["sex", "age", "income"]:
    feature_frame = users.reindex(columns=[Columns.User, feature])
    feature_frame.columns = ["id", "value"]
    feature_frame["feature"] = feature
    user_features_frames.append(feature_frame)
user_features = pd.concat(user_features_frames)
user_features.head()

        id value feature
0   973171     М     sex
1   962099     М     sex
3   721985     Ж     sex
4   704055     Ж     sex
5  1037719     М     sex

In [33]:
# оставляем у df users только тех, кто попал в train
items = items.loc[items[Columns.Item].isin(train[Columns.Item])].copy()

In [34]:
items["genre"] = items["genres"].str.lower().str.replace(", ", ",", regex=False).str.split(",")
genre_feature = items[["item_id", "genre"]].explode("genre")
genre_feature.columns = ["id", "value"]
genre_feature["feature"] = "genre"
genre_feature.head()

      id       value feature
0  10711       драмы   genre
0  10711  зарубежные   genre
0  10711   детективы   genre
0  10711   мелодрамы   genre
1   2508  зарубежные   genre

In [35]:
content_feature = items.reindex(columns=[Columns.Item, "content_type"])
content_feature.columns = ["id", "value"]
content_feature["feature"] = "content_type"
content_feature.head()

      id value       feature
0  10711  film  content_type
1   2508  film  content_type
2  10716  film  content_type
3   7868  film  content_type
4  16268  film  content_type

In [36]:
items["director"] = items["directors"].str.lower().str.replace(", ", ",", regex=False).str.split(",")
director_feature = items[["item_id", "director"]].explode("director")
director_feature.columns = ["id", "value"]
director_feature["feature"] = "director"
director_feature.head()

      id             value   feature
0  10711  педро альмодовар  director
1   2508    скот армстронг  director
2  10716  адам п. калтраро  director
3   7868         эндрю хэй  director
4  16268  виктор садовский  director

In [37]:
items["country"] = items["countries"].str.lower().str.replace(", ", ",", regex=False).str.split(",")
country_feature = items[["item_id", "country"]].explode("country")
country_feature.columns = ["id", "value"]
country_feature["feature"] = "country"
country_feature.head()

      id           value  feature
0  10711         испания  country
1   2508             сша  country
2  10716          канада  country
3   7868  великобритания  country
4  16268            ссср  country

In [38]:
year_feature = items.reindex(columns=[Columns.Item, "release_year"])
year_feature.columns = ["id", "value"]
year_feature["feature"] = "release_year"
year_feature.head()

      id   value       feature
0  10711  2002.0  release_year
1   2508  2014.0  release_year
2  10716  2011.0  release_year
3   7868  2015.0  release_year
4  16268  1978.0  release_year

In [39]:
# Объединяем фичи
item_features = pd.concat((genre_feature, content_feature, country_feature, year_feature, director_feature))
item_features

          id           value   feature
0      10711           драмы     genre
0      10711      зарубежные     genre
0      10711       детективы     genre
0      10711       мелодрамы     genre
1       2508      зарубежные     genre
...      ...             ...       ...
15960  10632     амир камдин  director
15960  10632       эрик эгер  director
15961   4538   марк о’коннор  director
15961   4538  конор макмахон  director
15962   3206  михаил миронов  director

[107488 rows x 3 columns]

In [40]:
metrics_name = {
    'Precision': Precision,
    'Recall': Recall,
    'MAP': MAP,
}

metrics = {}
for metric_name, metric in metrics_name.items():
    for k in range(1, 11):
        metrics[f'{metric_name}@{k}'] = metric(k=k)


pprint(metrics)

{'MAP@1': MAP(k=1, divide_by_k=False),
 'MAP@10': MAP(k=10, divide_by_k=False),
 'MAP@2': MAP(k=2, divide_by_k=False),
 'MAP@3': MAP(k=3, divide_by_k=False),
 'MAP@4': MAP(k=4, divide_by_k=False),
 'MAP@5': MAP(k=5, divide_by_k=False),
 'MAP@6': MAP(k=6, divide_by_k=False),
 'MAP@7': MAP(k=7, divide_by_k=False),
 'MAP@8': MAP(k=8, divide_by_k=False),
 'MAP@9': MAP(k=9, divide_by_k=False),
 'Precision@1': Precision(k=1),
 'Precision@10': Precision(k=10),
 'Precision@2': Precision(k=2),
 'Precision@3': Precision(k=3),
 'Precision@4': Precision(k=4),
 'Precision@5': Precision(k=5),
 'Precision@6': Precision(k=6),
 'Precision@7': Precision(k=7),
 'Precision@8': Precision(k=8),
 'Precision@9': Precision(k=9),
 'Recall@1': Recall(k=1),
 'Recall@10': Recall(k=10),
 'Recall@2': Recall(k=2),
 'Recall@3': Recall(k=3),
 'Recall@4': Recall(k=4),
 'Recall@5': Recall(k=5),
 'Recall@6': Recall(k=6),
 'Recall@7': Recall(k=7),
 'Recall@8': Recall(k=8),
 'Recall@9': Recall(k=9)}

Обучение

In [41]:
dataset = Dataset.construct(
    interactions_df=train,
    user_features_df=user_features,
    cat_user_features=["sex", "age", "income"],
    item_features_df=item_features,
    cat_item_features=["genre", "content_type", "director", "country", "release_year"],
)
TEST_USERS = test[Columns.User].unique()

In [42]:
dataset.interactions.df

         user_id  item_id  weight   datetime
0              0        0     3.0 2021-05-11
1              1        1     3.0 2021-05-29
2              2        2     1.0 2021-05-09
3              3        3     3.0 2021-07-05
4              4        0     3.0 2021-04-30
...          ...      ...     ...        ...
5476244    69627      219     3.0 2021-08-02
5476245    40052      132     1.0 2021-05-12
5476246   896790      318     1.0 2021-08-13
5476247   206604     2546     3.0 2021-04-13
5476249     7236     1609     3.0 2021-04-19

[4985269 rows x 4 columns]

In [43]:
K_RECOS = 10

model = ImplicitItemKNNWrapperModel(model=BM25Recommender(K=100, K1=0.05, B=0.1, num_threads=2))
model.fit(dataset)
recos = model.recommend(
    users=TEST_USERS,
    dataset=dataset,
    k=K_RECOS,
    filter_viewed=True,
)

In [45]:
model.recommend(
    users=[123],
    dataset=dataset,
    k=K_RECOS,
    filter_viewed=True,
)

   user_id  item_id         score  rank
0      123     7571  25662.054643     1
1      123     7582  24845.530464     2
2      123    16166  23719.672696     3
3      123     1105  21246.525855     4
4      123    10761  20835.562336     5
5      123     3182  19528.632211     6
6      123     9506  18000.015473     7
7      123    11756  17670.804086     8
8      123     5411  16507.992780     9
9      123    13018  16034.600122    10

In [46]:
results = []
model_quality = {'model': 'BM25Recommender'}
metric_values = calc_metrics(metrics, recos, test, train)
model_quality.update(metric_values)
results.append(model_quality)

df_quality = pd.DataFrame(results).T

df_quality.columns = df_quality.iloc[0]

df_quality.drop('model', inplace=True)

In [51]:
dill_file = Path().cwd().parent / 'data' / 'weights'

with open(dill_file / 'BM25Recommender_0.095432.dill', 'wb') as f:
    dill.dump(model, f)

In [53]:
dill_file = Path().cwd().parent / 'data'

with open(dill_file / 'dataset_BM25Recommender_0.095432.dill', 'wb') as f:
    dill.dump(dataset, f)

Подбор гиперпараметров

In [54]:
dataset = Dataset.construct(
    interactions_df=train,
    user_features_df=user_features,
    cat_user_features=["sex", "age", "income"],
    item_features_df=item_features,
    cat_item_features=["genre", "content_type", "director", "country", "release_year"],
)
TEST_USERS = test[Columns.User].unique()

results_opto = []

def objective(trial):
    # общие параметры
    K_RECOS = 10
    RANDOM_STATE = 42

    reco_model = trial.suggest_categorical("reco_model", ["BM25Recommender",
                                                          "CosineRecommender",
                                                          "TFIDFRecommender"])
    model_quality_opto = {"model": f"{reco_model}_{trial.number}"}

    if reco_model == "BM25Recommender":
        # гиперпараметры для BM25Recommender
        K = trial.suggest_int("K", 100, 500, 50, log=False)
        K1 = trial.suggest_float("K1", 0.01, 0.09, log=False)
        B = trial.suggest_float("B", 0.01, 0.5, log=False)
        # Инициализация BM25Recommender
        model = ImplicitItemKNNWrapperModel(model=BM25Recommender(K=K, K1=K1, B=B, num_threads=2))

    elif reco_model == "CosineRecommender":
        # гиперпараметры для CosineRecommender
        K = trial.suggest_int("K", 50, 200, 50, log=False)
        # Инициализация CosineRecommender
        model = ImplicitItemKNNWrapperModel(model=CosineRecommender(K=K))

    elif reco_model == "TFIDFRecommender":
        # гиперпараметры для TFIDFRecommender
        K = trial.suggest_int("K", 10, 100, 20, log=False)
        # Инициализация TFIDFRecommender
        model = ImplicitItemKNNWrapperModel(model=TFIDFRecommender(K=K))

    # обучение модели
    model.fit(dataset)
    recos = model.recommend(
        users=TEST_USERS,
        dataset=dataset,
        k=K_RECOS,
        filter_viewed=True,
    )

    # Подсчет метрик
    metric_values = calc_metrics(metrics, recos, test, train)
    model_quality_opto.update(metric_values)
    results_opto.append(model_quality_opto)

    return metric_values.get('MAP@10') # максимизируемая метрика

In [55]:
# запуск подбора гиперпараметров
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

pprint(f"Number of finished trials: {len(study.trials)}")
trial = study.best_trial
pprint(f"Best trial: {trial}")

[I 2023-11-29 15:47:29,448] A new study created in memory with name: no-name-89e4cc15-5562-46b9-89be-8d72908dc58a
[I 2023-11-29 15:47:42,409] Trial 0 finished with value: 0.07926813878289789 and parameters: {'reco_model': 'CosineRecommender', 'K': 100}. Best is trial 0 with value: 0.07926813878289789.
[I 2023-11-29 15:47:54,833] Trial 1 finished with value: 0.08046764264771092 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 70}. Best is trial 1 with value: 0.08046764264771092.
[I 2023-11-29 15:48:08,315] Trial 2 finished with value: 0.08068690081724368 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 90}. Best is trial 2 with value: 0.08068690081724368.
[I 2023-11-29 15:48:21,345] Trial 3 finished with value: 0.08068690081724368 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 90}. Best is trial 2 with value: 0.08068690081724368.
[I 2023-11-29 15:48:34,859] Trial 4 finished with value: 0.07948747637554937 and parameters: {'reco_model': 'CosineRecommender', 'K': 150}. Best is trial 2 with value: 0.08068690081724368.
[I 2023-11-29 15:48:47,640] Trial 5 finished with value: 0.08737094263037516 and parameters: {'reco_model': 'BM25Recommender', 'K': 150, 'K1': 0.0136338422718082, 'B': 0.35827714097104557}. Best is trial 5 with value: 0.08737094263037516.
[I 2023-11-29 15:49:00,144] Trial 6 finished with value: 0.07868501170457856 and parameters: {'reco_model': 'CosineRecommender', 'K': 50}. Best is trial 5 with value: 0.08737094263037516.
[I 2023-11-29 15:49:12,582] Trial 7 finished with value: 0.07868501170457856 and parameters: {'reco_model': 'CosineRecommender', 'K': 50}. Best is trial 5 with value: 0.08737094263037516.
[I 2023-11-29 15:49:25,792] Trial 8 finished with value: 0.08068690081724368 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 90}. Best is trial 5 with value: 0.08737094263037516.
[I 2023-11-29 15:49:40,138] Trial 9 finished with value: 0.0875280253989258 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.0350090593082321, 'B': 0.12852349255347129}. Best is trial 9 with value: 0.0875280253989258.
[I 2023-11-29 15:49:54,301] Trial 10 finished with value: 0.08842444841266099 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06410501916908495, 'B': 0.032986424683979665}. Best is trial 10 with value: 0.08842444841266099.
[I 2023-11-29 15:50:08,487] Trial 11 finished with value: 0.08856032042979732 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06886161318993778, 'B': 0.024941801048214012}. Best is trial 11 with value: 0.08856032042979732.
[I 2023-11-29 15:50:22,580] Trial 12 finished with value: 0.08856588823174437 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07319650658561772, 'B': 0.01106034082683548}. Best is trial 12 with value: 0.08856588823174437.
[I 2023-11-29 15:50:36,783] Trial 13 finished with value: 0.08835193944675851 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.08544499408241164, 'B': 0.03120575781672795}. Best is trial 12 with value: 0.08856588823174437.
[I 2023-11-29 15:50:50,381] Trial 14 finished with value: 0.08285129187189567 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.07159733477006476, 'B': 0.18400417249039777}. Best is trial 12 with value: 0.08856588823174437.
[I 2023-11-29 15:51:03,978] Trial 15 finished with value: 0.0885669249573265 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.061732858656703714, 'B': 0.013112422899358135}. Best is trial 15 with value: 0.0885669249573265.
[I 2023-11-29 15:51:17,832] Trial 16 finished with value: 0.08247162944197857 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.049205703932095606, 'B': 0.2749527790180162}. Best is trial 15 with value: 0.0885669249573265.
[I 2023-11-29 15:51:30,943] Trial 17 finished with value: 0.06460381247379222 and parameters: {'reco_model': 'BM25Recommender', 'K': 300, 'K1': 0.08373382269106795, 'B': 0.4846913097377126}. Best is trial 15 with value: 0.0885669249573265.
[I 2023-11-29 15:51:43,869] Trial 18 finished with value: 0.08696011805572101 and parameters: {'reco_model': 'BM25Recommender', 'K': 300, 'K1': 0.05264156106535195, 'B': 0.11000939807274339}. Best is trial 15 with value: 0.0885669249573265.
[I 2023-11-29 15:51:58,437] Trial 19 finished with value: 0.08857409094654696 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07592451535297821, 'B': 0.01345881712652398}. Best is trial 19 with value: 0.08857409094654696.
[I 2023-11-29 15:52:11,847] Trial 20 finished with value: 0.0848208482471961 and parameters: {'reco_model': 'BM25Recommender', 'K': 350, 'K1': 0.0897370255327255, 'B': 0.11211846235409609}. Best is trial 19 with value: 0.08857409094654696.
[I 2023-11-29 15:52:25,761] Trial 21 finished with value: 0.08857853597738581 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07445310144061881, 'B': 0.02329643412985356}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:52:39,637] Trial 22 finished with value: 0.08665459693637252 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07737438654264144, 'B': 0.08576088683579572}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:52:53,859] Trial 23 finished with value: 0.08759393328657503 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.06140054363853001, 'B': 0.07144827221239358}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:53:07,286] Trial 24 finished with value: 0.08855498748525321 and parameters: {'reco_model': 'BM25Recommender', 'K': 350, 'K1': 0.07907959469776095, 'B': 0.011322906114917338}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:53:21,331] Trial 25 finished with value: 0.08426404506643519 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.05858408848340302, 'B': 0.1844949372141123}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:53:34,562] Trial 26 finished with value: 0.08738616728068521 and parameters: {'reco_model': 'BM25Recommender', 'K': 250, 'K1': 0.07257792226314896, 'B': 0.0692540624751355}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:53:48,998] Trial 27 finished with value: 0.08333883518251498 and parameters: {'reco_model': 'BM25Recommender', 'K': 350, 'K1': 0.07891226056761685, 'B': 0.1555159853496596}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:53:59,700] Trial 28 finished with value: 0.0791741576007455 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 30}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:54:12,351] Trial 29 finished with value: 0.07948747637554937 and parameters: {'reco_model': 'CosineRecommender', 'K': 150}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:54:24,535] Trial 30 finished with value: 0.07948747637554937 and parameters: {'reco_model': 'CosineRecommender', 'K': 150}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:54:38,423] Trial 31 finished with value: 0.08854615359413598 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.06869522050216617, 'B': 0.012845161885913312}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:54:52,543] Trial 32 finished with value: 0.08776892276783228 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07347599221676313, 'B': 0.05546658746327858}. Best is trial 21 with value: 0.08857853597738581.
[I 2023-11-29 15:55:06,491] Trial 33 finished with value: 0.08857946500875995 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.08055604181292794, 'B': 0.011710092213616182}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:55:16,876] Trial 34 finished with value: 0.07703858584101313 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 10}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:55:30,614] Trial 35 finished with value: 0.08693725695367656 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.08338742657587411, 'B': 0.07130409836837534}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:55:44,782] Trial 36 finished with value: 0.08750644058171575 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07968617256806973, 'B': 0.05898976267467124}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:55:56,225] Trial 37 finished with value: 0.08046764264771092 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 70}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:56:10,312] Trial 38 finished with value: 0.07964257735091533 and parameters: {'reco_model': 'CosineRecommender', 'K': 200}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:56:24,863] Trial 39 finished with value: 0.08591481589502245 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.08969692524042108, 'B': 0.08936171043225757}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:56:39,156] Trial 40 finished with value: 0.08805462000567135 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.06537947462604332, 'B': 0.054204401323270424}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:56:53,627] Trial 41 finished with value: 0.08855913345036794 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07464701897207604, 'B': 0.019170285620561146}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:57:07,788] Trial 42 finished with value: 0.0885490397937172 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.0745167802923702, 'B': 0.016463753694001007}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:57:22,470] Trial 43 finished with value: 0.08850228139555946 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06577940210426422, 'B': 0.010326673446821453}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:57:37,513] Trial 44 finished with value: 0.08816008073519202 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.0706385161695455, 'B': 0.04571695443966202}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:57:49,908] Trial 45 finished with value: 0.08046764264771092 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 70}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:58:05,061] Trial 46 finished with value: 0.08767580727254726 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.08065039447015138, 'B': 0.05375866043061264}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:58:17,177] Trial 47 finished with value: 0.07926813878289789 and parameters: {'reco_model': 'CosineRecommender', 'K': 100}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:58:32,769] Trial 48 finished with value: 0.08592229247844561 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07614727145136455, 'B': 0.10391485611863858}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:58:46,206] Trial 49 finished with value: 0.08831863148497339 and parameters: {'reco_model': 'BM25Recommender', 'K': 350, 'K1': 0.060343216118750015, 'B': 0.04446166272621372}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:58:59,919] Trial 50 finished with value: 0.08504312228448695 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.06804617630627513, 'B': 0.14163771408684125}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:59:14,222] Trial 51 finished with value: 0.08856435161658845 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06967955785838209, 'B': 0.011905845121904702}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:59:28,580] Trial 52 finished with value: 0.08832421661973351 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.0719779025897106, 'B': 0.03796827105552129}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:59:42,965] Trial 53 finished with value: 0.08847182003051603 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.015118797265464355, 'B': 0.03603734131575349}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 15:59:56,965] Trial 54 finished with value: 0.08703370661929594 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.065728717540197, 'B': 0.08660410893508319}. Best is trial 33 with value: 0.08857946500875995.
[I 2023-11-29 16:00:11,427] Trial 55 finished with value: 0.08859721092713521 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07663166468644847, 'B': 0.013984294112838504}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:00:25,819] Trial 56 finished with value: 0.08835189926406456 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.08512258487075278, 'B': 0.030961226486128195}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:00:39,910] Trial 57 finished with value: 0.08816573606286808 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07674840337362725, 'B': 0.04278272757863075}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:00:53,565] Trial 58 finished with value: 0.08690488518382272 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.08216340621561993, 'B': 0.07375676431765053}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:01:06,163] Trial 59 finished with value: 0.07964257735091533 and parameters: {'reco_model': 'CosineRecommender', 'K': 200}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:01:17,378] Trial 60 finished with value: 0.08021362348230696 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 50}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:01:31,658] Trial 61 finished with value: 0.0885743248998169 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07173056081336733, 'B': 0.013293388339669952}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:01:45,830] Trial 62 finished with value: 0.08835263096858204 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07661992561189868, 'B': 0.03336723031060665}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:02:00,072] Trial 63 finished with value: 0.08839931943856959 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07262918766204411, 'B': 0.03297743098181306}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:02:14,159] Trial 64 finished with value: 0.08840893887087527 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07978884112588554, 'B': 0.028416863594026287}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:02:28,923] Trial 65 finished with value: 0.08854864535264863 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.0846374368330701, 'B': 0.010337251771132155}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:02:42,979] Trial 66 finished with value: 0.08778490623929676 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.06889077644319343, 'B': 0.058462347065326936}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:02:57,933] Trial 67 finished with value: 0.08691832340044058 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07687358397737026, 'B': 0.07742567522249252}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:03:12,191] Trial 68 finished with value: 0.0868173801166035 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.06148675424705896, 'B': 0.0998797250978547}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:03:26,005] Trial 69 finished with value: 0.08839718466680051 and parameters: {'reco_model': 'BM25Recommender', 'K': 400, 'K1': 0.07368871306370339, 'B': 0.032659543700574875}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:03:40,224] Trial 70 finished with value: 0.08845185579902902 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.0562494150303127, 'B': 0.01053540927321515}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:03:54,246] Trial 71 finished with value: 0.08856159490107164 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.07065697813406292, 'B': 0.011906856947318762}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:04:08,780] Trial 72 finished with value: 0.08814303594578823 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06841162318915275, 'B': 0.05082298955720849}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:04:23,573] Trial 73 finished with value: 0.0884086567318972 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.08117239008260402, 'B': 0.027757201981905608}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:04:38,480] Trial 74 finished with value: 0.08764755250032676 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06372330696698743, 'B': 0.06786574883535185}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:04:52,949] Trial 75 finished with value: 0.08787393332358143 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07749547923231878, 'B': 0.05017265772640386}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:05:03,585] Trial 76 finished with value: 0.07703858584101313 and parameters: {'reco_model': 'TFIDFRecommender', 'K': 10}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:05:16,120] Trial 77 finished with value: 0.07948747637554937 and parameters: {'reco_model': 'CosineRecommender', 'K': 150}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:05:30,041] Trial 78 finished with value: 0.0885148509222629 and parameters: {'reco_model': 'BM25Recommender', 'K': 350, 'K1': 0.07157296994660775, 'B': 0.027175640355577766}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:05:44,591] Trial 79 finished with value: 0.08855800558063391 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.0788032267318267, 'B': 0.01003790838327321}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:05:58,640] Trial 80 finished with value: 0.0855225942267866 and parameters: {'reco_model': 'BM25Recommender', 'K': 450, 'K1': 0.07459699277832971, 'B': 0.11864249325021277}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:06:13,236] Trial 81 finished with value: 0.0885632092325558 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06892902711705548, 'B': 0.025632093078231326}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:06:28,132] Trial 82 finished with value: 0.08855192776616519 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06937344914842444, 'B': 0.02660381096890497}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:06:42,191] Trial 83 finished with value: 0.08749717578016486 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.0737388527140233, 'B': 0.0641937182706232}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:06:54,971] Trial 84 finished with value: 0.08815874781960768 and parameters: {'reco_model': 'BM25Recommender', 'K': 300, 'K1': 0.07101049279185476, 'B': 0.0453271740707683}. Best is trial 55 with value: 0.08859721092713521.
[I 2023-11-29 16:07:09,284] Trial 85 finished with value: 0.08855372254142849 and parameters: {'reco_model': 'BM25Recommender', 'K': 500, 'K1': 0.06614936856680806, 'B': 0.023745461298042968}. Best is trial 55 with value: 0.08859721092713521.

'Number of finished trials: 100'
('Best trial: FrozenTrial(number=55, state=TrialState.COMPLETE, '
 'values=[0.08859721092713521], datetime_start=datetime.datetime(2023, 11, 29, '
 '15, 59, 56, 965689), datetime_complete=datetime.datetime(2023, 11, 29, 16, '
 "0, 11, 427138), params={'reco_model': 'BM25Recommender', 'K': 500, 'K1': "
 "0.07663166468644847, 'B': 0.013984294112838504}, user_attrs={}, "
 "system_attrs={}, intermediate_values={}, distributions={'reco_model': "
 "CategoricalDistribution(choices=('BM25Recommender', 'CosineRecommender', "
 "'TFIDFRecommender')), 'K': IntDistribution(high=500, log=False, low=100, "
 "step=50), 'K1': FloatDistribution(high=0.09, log=False, low=0.01, "
 "step=None), 'B': FloatDistribution(high=0.5, log=False, low=0.01, "
 'step=None)}, trial_id=55, value=None)')

In [56]:
df_quality = pd.DataFrame(results_opto).T

df_quality.columns = df_quality.iloc[0]

df_quality.drop('model', inplace=True)

In [57]:
df_quality = df_quality.T.drop_duplicates().T
df_quality.style.highlight_max(color='lightgreen', axis=1)

Обучение модели с лучшими гиперпараметрами

In [58]:
users_inv_mapping = dict(enumerate(train['user_id'].unique()))
users_mapping = {v: k for k, v in users_inv_mapping.items()}


items_inv_mapping = dict(enumerate(train['item_id'].unique()))
items_mapping = {v: k for k, v in items_inv_mapping.items()}

In [59]:
def get_coo_matrix(df,
                   user_col='user_id',
                   item_col='item_id',
                   weight_col=None,
                   users_mapping=None,
                   items_mapping=None):
    if weight_col:
        weights = df[weight_col].astype(np.float32)
    else:
        weights = np.ones(len(df), dtype=np.float32)

    interaction_matrix = sp.sparse.coo_matrix((
        weights,
        (
            df[user_col].map(users_mapping.get),
            df[item_col].map(items_mapping.get)
        )
    ))
    return interaction_matrix
interaction_matrix = get_coo_matrix(train, weight_col='weight',
                                    users_mapping=users_mapping,
                                    items_mapping=items_mapping)

Обучение

In [61]:
userknn = BM25Recommender(K=50, K1=0.012556305101247701, B=0.05289835164246949, num_threads=2)
userknn.fit(interaction_matrix)

  0%|          | 0/15565 [00:00<?, ?it/s]

In [64]:
dill_file = Path().cwd().parent / 'data' / 'weights'

with open(dill_file / 'userknn_BM25Recommender.dill', 'wb') as f:
    dill.dump(userknn, f)

In [65]:
dill_file = Path().cwd().parent / 'data'

with open(dill_file / 'dataset_userknn_BM25Recommender.dill', 'wb') as f:
    dill.dump(dataset, f)